#pragma config(Motor,  port2,           climber,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           turret,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           servturret,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port5,           claw1,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port6,           claw2,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port8,           slidestop,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           arm,           tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*                                              \
| Controls:
|   Climb: Up/Down on Right Joystick
|   Hold Climbing Power: 7L
|   Brake Slider: 7D in/out
|
|
|
|
|
\                                              */

bool lockrelease = false;
int rightY = 0;
int climbSpeed;
int climbShift;
int clawPos;

task Lift() {
	while(true) {
		climbSpeed = rightY + climbShift;
		if(!lockrelease) {
			motor[climber] = climbSpeed;
		}
		if(vexRT[Btn7R]) {
			climbShift = 0;
		}
		if(vexRT[Btn7L]) {
			while(vexRT[Btn7L]) {
				climbShift = vexRT[Ch2];
			}
			climbSpeed = climbShift;
			motor[climber] = climbSpeed;
			wait1Msec(400);
		}
	}
}

task Manipulation() {
	while(true) {
		if(vexRT[Btn6D]) { //Arm swivel
			motor[turret] = vexRT[Ch4];
		} else {
			motor[turret] = 0;
		}
		if(vexRT[Btn6U]) { // Arm up/down
			int asdf = 1;
			motor[arm] = vexRT[Ch3];
		} else {
			int asdf = 2;
			motor[arm] = 0;
		}
		if(vexRT[Btn8L]) {
			clawPos++;
			wait1Msec(2);
		}
		if(vexRT[Btn8R]) {
			clawPos = -127;
		}
		motor[claw1] = clawPos;
		motor[claw2] = -clawPos;
	}
}

task AutoFunctions() {

}

task main() {
	StartTask(Lift);
	StartTask(Manipulation);
  StartTask(AutoFunctions);
	bool running = true;
	while(running) {
		//Still Alive!
		rightY = vexRT[Ch2];
	}
}
