#pragma config(Sensor, dgtl1,  sMotor1f,       sensorDigitalIn)
#pragma config(Sensor, dgtl2,  sMotor1r,       sensorDigitalIn)
#pragma config(Sensor, dgtl3,  sMotor2f,       sensorDigitalIn)
#pragma config(Sensor, dgtl4,  sMotor2r,       sensorDigitalIn)
#pragma config(Motor,  port2,           LeftDrive,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           sMotor1,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           servo1,        tmotorServoStandard, openLoop)
#pragma config(Motor,  port5,           servo2,        tmotorServoStandard, openLoop)
#pragma config(Motor,  port6,           servo3,        tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           servo4,        tmotorServoStandard, openLoop)
#pragma config(Motor,  port8,           sMotor2,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           RightDrive,    tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int threshold = 10;

task Drive() {
  int RightX;
  int RightY;
  while(true) {
    if(RightY > threshold) { // Forwards
      motor[LeftDrive] = (RightY + RightX)^2/127;
      motor[RightDrive] = (RightY - RightX)^2/127;
    }  else if(RightY < -threshold) { // Backwards
      motor[LeftDrive] = (RightY + RightX)^2/127;
      motor[RightDrive] = (RightY - RightX)^2/127;
    }  else if((abs(RightX) > threshold) && (abs(RightY) < threshold)) { // Turning in Place
      motor[LeftDrive] = RightX;
      motor[RightDrive] = (-1 * RightX);
    }  else { // If no controls held, disable motors
      motor[LeftDrive] = 0;
      motor[RightDrive] = 0;
    }
  }
}

task Arm() {
  int LeftX;
  int LeftY;
  while(true) {
    LeftX = vexRT[Ch4];
    LeftY = vexRT[Ch3];
    if(vexRT[Btn6U]) {
      if((LeftY > threshold) && !SensorValue[sMotor1f]) {
        motor[sMotor1] = LeftY;
      } else if((LeftY < -threshold) && !SensorValue[sMotor1r]) {
        motor[sMotor1] = LeftY;
      } else {
        motor[sMotor1] = 0;
      }
    } else {
      motor[sMotor1] = 0;
    }

    if(vexRT[Btn6D]) {
      if((LeftY > threshold) && !SensorValue[sMotor2f]) {
        motor[sMotor2] = LeftY;
      } else if((LeftY < -threshold) && !SensorValue[sMotor2r]) {
        motor[sMotor2] = LeftY;
      } else {
        motor[sMotor2] = 0;
      }
    } else {
      motor[sMotor2] = 0;
    }


    if(vexRT[Btn5U]) {
      motor[servo1] = LeftY;
    }
    if(vexRT[Btn5D]) {
      motor[servo2] = LeftY;
    }

    if(vexRT[Btn7L]) {
      motor[servo3] = -128;
    } else if(vexRT[Btn7U]) {
      motor[servo3] = 0;
    } else if(vexRT[Btn7R]) {
      motor[servo3] = 127;
    }

    if(vexRT[Btn8L]) {
      motor[servo4] = -128;
    } else if(vexRT[Btn8U]) {
      motor[servo4] = 0;
    } else if(vexRT[Btn8R]) {
      motor[servo4] = 127;
    }
  }
}
task main() {
  StartTask(Drive);
  StartTask(Arm);
  int on = 1;
  while(on){};
}
